# Class cis::el7all
#
# Implements all CIS controls found the the RHEL7 benchmark. Use this class as
# base if any deviations are necessary.
#

class cis::el7all {
  include cis::el7::a
  include cis::el7::b
  include cis::el7::c
  include cis::el7::d
  include cis::el7::e
  include cis::el7::f
  include cis::el7::g
  include cis::el7::h
  include cis::el7::i
  include cis::el7::j
  include cis::el7::k
  include cis::el7::l
  include cis::el7::m
  include cis::el7::n
  include cis::el7::o
  include cis::el7::p
  include cis::el7::q
  include cis::el7::r
  include cis::el7::s
  include cis::el7::t
  include cis::el7::u
  include cis::el7::v
  include cis::el7::w
  include cis::el7::x
  include cis::el7::y
  include cis::el7::z
  include cis::el7::aa
  include cis::el7::bb
  include cis::el7::cc
  include cis::el7::dd
  include cis::el7::ee
  include cis::el7::ff
  include cis::el7::gg
  include cis::el7::hh
  include cis::el7::ii
  include cis::el7::jj
  include cis::el7::kk
  include cis::el7::ll
  include cis::el7::mm
  include cis::el7::nn
  include cis::el7::oo
  include cis::el7::pp
  include cis::el7::qq
  include cis::el7::rr
  include cis::el7::ss
  include cis::el7::tt
  include cis::el7::uu
  include cis::el7::vv
  include cis::el7::ww
  include cis::el7::xx
  include cis::el7::yy
  include cis::el7::zz
  include cis::el7::aaa
  include cis::el7::bbb
  include cis::el7::ccc
  include cis::el7::ddd
  include cis::el7::eee
  include cis::el7::fff
  include cis::el7::ggg
  include cis::el7::hhh
  include cis::el7::iii
  include cis::el7::jjj
  include cis::el7::kkk
  include cis::el7::lll
  include cis::el7::mmm
  include cis::el7::nnn
  include cis::el7::ooo
  include cis::el7::ppp
  include cis::el7::qqq
  include cis::el7::rrr
  include cis::el7::sss
  include cis::el7::ttt
  include cis::el7::uuu
  include cis::el7::vvv
  include cis::el7::www
  include cis::el7::xxx
  include cis::el7::yyy
  include cis::el7::zzz
  include cis::el7::a1
  include cis::el7::a2
  include cis::el7::a3
  include cis::el7::a4
  include cis::el7::a5
  include cis::el7::a6
  include cis::el7::a7
  include cis::el7::a8
  include cis::el7::a9
  include cis::el7::a10
  include cis::el7::b1
  include cis::el7::b2
  include cis::el7::b3
  include cis::el7::b4
  include cis::el7::b5
  include cis::el7::b6
  include cis::el7::b7
  include cis::el7::b8
  include cis::el7::b9
  include cis::el7::b10
  include cis::el7::c1
  include cis::el7::c2
  include cis::el7::c3
  include cis::el7::c4
  include cis::el7::c5
  include cis::el7::c6
  include cis::el7::c7
  include cis::el7::c8
  include cis::el7::c9
  include cis::el7::c10
  include cis::el7::d1
  include cis::el7::d2
  include cis::el7::d3
  include cis::el7::d4
  include cis::el7::d5
  include cis::el7::d6
  include cis::el7::d7
  include cis::el7::d8
  include cis::el7::d9
  include cis::el7::d10
  include cis::el7::e1
  include cis::el7::e2
  include cis::el7::e3
  include cis::el7::e4
  include cis::el7::e5
  include cis::el7::e6
  include cis::el7::e7
  include cis::el7::e8
  include cis::el7::e9
  include cis::el7::f1
  include cis::el7::f2
  include cis::el7::f3
  include cis::el7::f4
  include cis::el7::f5
  include cis::el7::f6
  include cis::el7::f7
  include cis::el7::f8
  include cis::el7::f9
  include cis::el7::f10
  include cis::el7::g1
  include cis::el7::g2
  include cis::el7::g3
  include cis::el7::g4
  include cis::el7::g5
  include cis::el7::g6
  include cis::el7::g7
  include cis::el7::g8
  include cis::el7::g9
  include cis::el7::g10
  include cis::el7::h1
  include cis::el7::h2
  include cis::el7::h3
  include cis::el7::h4
  include cis::el7::h5
  include cis::el7::h6
  include cis::el7::h7
  include cis::el7::h8
  include cis::el7::h9
  include cis::el7::h10
  include cis::el7::i1
  include cis::el7::i2
}
